export const ACCELERATION_INCREMENT = "ACCELERATION_INCREMENT";
export const ACCELERATION_DECREMENT = "ACCELERATION_DECREMENT";
export const BREAKING_INCREMENT = "BREAKING_INCREMENT";
export const BREAKING_DECREMENT = "BREAKING_DECREMENT";
export const CLUTCHING_INCREMENT = "CLUTCHING_INCREMENT";
export const CLUTCHING_DECREMENT = "CLUTCHING_DECREMENT";
export const SET_GEAR = "SET_GEAR";

export const SPEED_INCREMENT = "SPEED_INCREMENT";
export const SPEED_DECREMENT = "SPEED_DECREMENT";

export const RPM_INCREMENT = "RPM_INCREMENT";
export const RPM_DECREMENT = "RPM_DECREMENT";
