export const ACCELERATION_INCREMENT = "ACCELERATION_INCREMENT";
export const ACCELERATION_DECREMENT = "ACCELERATION_DECREMENT";
export const BREAKING_INCREMENT = "BREAKING_INCREMENT";
export const BREAKING_DECREMENT = "BREAKING_DECREMENT";
export const CLUTCHING_INCREMENT = "CLUTCHING_INCREMENT";
export const CLUTCHING_DECREMENT = "CLUTCHING_DECREMENT";
export const SET_GEAR = "SET_GEAR";
