export const ACCELERATION_INCREMENT = "ACCELERATION_INCREMENT";
export const ACCELERATION_DECREMENT = "ACCELERATION_DECREMENT";
export const ACCELERATION_HIGHER_THAN_100 = "ACCELERATION_HIGHER_THAN_100";
export const ACCELERATION_LOWER_THAN_0 = "ACCELERATION_LOWER_THAN_0";
